# Site settings
title: Runaway Dunaway
email: jessica_barstis@bostonconservatory.edu
description: "I like sparkles. And unicorns. And probably you."
url: "http://mavant.com"
baseurl: "jdb"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jessicadunaway
  - title: facebook
    url: http://facebook.com/jessica.barstis

# Postal address (add as many lines as necessary)
address:
  - line: New York, NY

# Build settings
markdown: kramdown
permalink: pretty
